name: Run Circuit SK

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.1

    - name: Install dependencies
      run: |
        pip3 install -r scripts/requirements.txt

    - name: Generate Parameters for circuit and Run Tests
      run: |
        python3 scripts/circuit_sk.py -n 4096 -qis '[                                      
            27424203952895201, 
            27424203952895203
        ]' -t 65537
        cargo build
        cargo test --release --features bench -- --nocapture
